### ISSUE TITLE
 例子的三角形demo编译报错

### ISSUE THREAD

**Issue by ElyotChou** [ThisisGame/makegameengineatnight#3]
F:\makegameengineatnight-main\samples\draw_polygon\draw_quad\untitled\main.cpp(138): error C2065: 'trans': undeclared identifier

例子的三角形demo编译报错 但 trans有定义。

**Comment by ThisisGame** [comment]
是否删除了某一行代码，138行并没有用到 `trans`?
![图片](https://user-images.githubusercontent.com/17882033/142790730-edea40f0-b7cb-4c7d-8881-1fedc4629da3.png)

**Comment by ElyotChou** [comment]
![image](https://user-images.githubusercontent.com/12494909/142825402-80ed525f-0e4b-4c15-9e64-8014be604cdd.png)

glm有正确拷贝过去哦。。我还是没找到原因 拜托你了。

**Comment by ThisisGame** [comment]
先找身边朋友帮看看，没解决的话加我qq吧，我远程看下。

**Comment by 2563495284** [comment]
解决方法：UTF-8转换成为GBK

**Comment by ThisisGame** [comment]
> 

感谢。
目前main分支已经转换为utf-8 with bom，如再遇到问题，可以进群聊。
